require('basic')
require('plugins')
require('keybindings')
require('colorscheme')
require('autocmd')

require('plugin-config/autopairs')
require('plugin-config/bufferline')
require('plugin-config/comment')
require('plugin-config/indent-line')
require('plugin-config/nvim-tree')
require('plugin-config/surround')
require('plugin-config/git')
require('plugin-config/navigator')
require('plugin-config/persistence')
require('plugin-config/treesitter')
require('plugin-config/dap')
require('plugin-config/eyeliner')
require('plugin-config/lualine')
require('plugin-config/toggleterm')

require('lsp/mason')
require('lsp/config')
require('lsp/null-ls')
require('lsp/ui')
